TOP_DIR = 
default:
	gcc -g clutch2.c ../../../templates/gsl2/gsl-interface.c \
	-DCONSOLE  -I../../../templates/gsl2 \
	-I../../../templates/fmi2 -lgsl -lgslcblas -lm  \
	-I../../../../build/install/include  -o clutch2

