INC = -I/usr/include/SDL2 -I./twinkle/TwinklebearDev-Lessons-master/include/
# You may need to change -std=c++11 to -std=c++0x if your compiler is a bit older
CXXFLAGS = -Wall -std=c++11 $(SDL_INCLUDE)  $(INC)
LDLIBS = -lSDL2  -lGLU -lGL  -lglut 

