INC = -I/usr/include/SDL2 -I/usr/include/eigen3

#-I./twinkle/TwinklebearDev-Lessons-master/include/
# You may need to change -std=c++11 to -std=c++0x if your compiler is a bit older
CXXFLAGS = -Wall  $(SDL_INCLUDE)  $(INC) -std=c++11 -Wno-deprecated -Wno-deprecated-declarations 
LDLIBS = -lSDL2  -lGLU -lGL  -lglut 

