---
stages:
  - build
  - test

build:bionic:
  stage: build
  script:
    - docker build -t umit/bionic:$(git rev-parse HEAD) -f Buildstuff/Dockerfile.bionic .
  tags:
    - shell

build:focal:
  stage: build
  script:
    - docker build -t umit/focal:$(git rev-parse HEAD) -f Buildstuff/Dockerfile.focal .
  tags:
    - shell

build:jammy:
  stage: build
  script:
    - docker build -t umit/jammy:$(git rev-parse HEAD) -f Buildstuff/Dockerfile.jammy .
  tags:
    - shell

build:buster:
  stage: build
  script:
    - docker build -t umit/buster:$(git rev-parse HEAD) -f Buildstuff/Dockerfile.buster .
  tags:
    - shell

build:bullseye:
  stage: build
  script:
    - docker build -t umit/bullseye:$(git rev-parse HEAD) -f Buildstuff/Dockerfile.bullseye .
  tags:
    - shell

build:bookworm:
  stage: build
  script:
    - docker build -t umit/bookworm:$(git rev-parse HEAD) -f Buildstuff/Dockerfile.bookworm .
  tags:
    - shell

build:mantic:
  stage: build
  script:
    - docker build -t umit/mantic:$(git rev-parse HEAD) -f Buildstuff/Dockerfile.mantic .
  tags:
    - shell

build:noble:
  stage: build
  script:
    - docker build -t umit/noble:$(git rev-parse HEAD) -f Buildstuff/Dockerfile.noble .
  tags:
    - shell

test:bionic:
  stage: test
  script:
    - docker run --workdir /home/gitlab-ci/umit umit/bionic:$(git rev-parse HEAD) bash run_tests.sh
  dependencies:
    - build:bionic
  tags:
    - shell

test:focal:
  stage: test
  script:
    - docker run --workdir /home/gitlab-ci/umit umit/focal:$(git rev-parse HEAD) bash run_tests.sh
  dependencies:
    - build:focal
  tags:
    - shell

test:jammy:
  stage: test
  script:
    - docker run --workdir /home/gitlab-ci/umit umit/jammy:$(git rev-parse HEAD) bash run_tests.sh
  dependencies:
    - build:jammy
  tags:
    - shell

test:buster:
  stage: test
  script:
    - docker run --workdir /home/gitlab-ci/umit umit/buster:$(git rev-parse HEAD) bash run_tests.sh
  dependencies:
    - build:buster
  tags:
    - shell

test:bullseye:
  stage: test
  script:
    - docker run --workdir /home/gitlab-ci/umit umit/bullseye:$(git rev-parse HEAD) bash run_tests.sh
  dependencies:
    - build:bullseye
  tags:
    - shell

test:bookworm:
  stage: test
  script:
    - docker run --workdir /home/gitlab-ci/umit umit/bookworm:$(git rev-parse HEAD) bash run_tests.sh
  dependencies:
    - build:bookworm
  tags:
    - shell

test:mantic:
  stage: test
  script:
    - docker run --workdir /home/gitlab-ci/umit umit/mantic:$(git rev-parse HEAD) bash run_tests.sh
  dependencies:
    - build:mantic
  tags:
    - shell

test:noble:
  stage: test
  script:
    - docker run --workdir /home/gitlab-ci/umit umit/noble:$(git rev-parse HEAD) bash run_tests.sh
  dependencies:
    - build:noble
  tags:
    - shell
