---
stages:
  - build
  - test

build:bionic:
  stage: build
  script:
    - docker build -t umit/bionic:$(git rev-parse HEAD) -f Buildstuff/Dockerfile.bionic .
  tags:
    - shell

build:focal:
  stage: build
  script:
    - docker build -t umit/focal:$(git rev-parse HEAD) -f Buildstuff/Dockerfile.focal .
  tags:
    - shell

build:stretch:
  stage: build
  script:
    - docker build -t umit/stretch:$(git rev-parse HEAD) -f Buildstuff/Dockerfile.stretch .
  tags:
    - shell

build:buster:
  stage: build
  script:
    - docker build -t umit/buster:$(git rev-parse HEAD) -f Buildstuff/Dockerfile.buster .
  tags:
    - shell

build:bullseye:
  stage: build
  script:
    - docker build -t umit/bullseye:$(git rev-parse HEAD) -f Buildstuff/Dockerfile.bullseye .
  tags:
    - shell

test:bionic:
  stage: test
  script:
    - docker run --workdir /home/gitlab-ci/umit umit/bionic:$(git rev-parse HEAD) bash run_tests.sh
  dependencies:
    - build:bionic
  tags:
    - shell

test:focal:
  stage: test
  script:
    - docker run --workdir /home/gitlab-ci/umit umit/focal:$(git rev-parse HEAD) bash run_tests.sh
  dependencies:
    - build:focal
  tags:
    - shell

test:stretch:
  stage: test
  script:
    - docker run --workdir /home/gitlab-ci/umit umit/stretch:$(git rev-parse HEAD) bash run_tests.sh
  dependencies:
    - build:stretch
  tags:
    - shell

test:buster:
  stage: test
  script:
    - docker run --workdir /home/gitlab-ci/umit umit/buster:$(git rev-parse HEAD) bash run_tests.sh
  dependencies:
    - build:buster
  tags:
    - shell

test:bullseye:
  stage: test
  script:
    - docker run --workdir /home/gitlab-ci/umit umit/bullseye:$(git rev-parse HEAD) bash run_tests.sh
  dependencies:
    - build:bullseye
  tags:
    - shell
