---
stages:
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: "recursive"

umit:
  stage: build
  script:
    - docker build -t umit/trusty:$(git rev-parse HEAD)            -f Dockerfile.trusty            .
    - docker build -t umit/trusty-cmake3.5.0:$(git rev-parse HEAD) -f Dockerfile.trusty-cmake3.5.0 .
    - docker build -t umit/xenial:$(git rev-parse HEAD)            -f Dockerfile.xenial            .
  tags:
    - shell

test:
  stage: test
  script:
    - docker run --workdir /home/gitlab-ci/umit umit/trusty:$(git rev-parse HEAD)            bash run_tests.sh
    - docker run --workdir /home/gitlab-ci/umit umit/trusty-cmake3.5.0:$(git rev-parse HEAD) bash run_tests.sh
    - docker run --workdir /home/gitlab-ci/umit umit/xenial:$(git rev-parse HEAD)            bash run_tests.sh
    - docker run --workdir /home/gitlab-ci/umit/build/install umit/xenial:$(git rev-parse HEAD) tar cz . > umit-$(git rev-parse HEAD).tar.gz
  dependencies:
    - umit
  artifacts:
    paths:
      - umit-*.tar.gz
  tags:
    - shell
