---
stages:
  - build
  - test

build:
  stage: build
  script:
    - echo hello
    - rm -rf build
    - mkdir build
    - cd build
    - cmake .. -G Ninja
    - ninja
    - cd ..
  tags:
    - shell
  when: always
  artifacts:
    paths:
    - build

test:
  stage: test
  script:
    - echo $(pwd)
    - ls
    - cd build
    - echo $(pwd)
    - ctest
    - cd ..
  tags:
    - shell
  dependencies:
    - build