FROM ubuntu:trusty
RUN apt-get update

#
# Some notes on the packages installed here where it may not be obvious why
# they are installed:
#
#  build-essential: for gcc
#              git: for being able to fetch submodules, since gitlab doesn't
#                   do this for us yet
#           psmisc: for killall
#  mpi-default-bin: for mpiexec
#        coreutils: for sha1sum
#
RUN apt-get install --yes \
        build-essential ninja-build git python bc psmisc \
        protobuf-compiler protobuf-c-compiler libprotobuf-dev \
        libsuitesparse-dev libzmqpp-dev libhdf5-dev \
        libopenmpi-dev libgsl0-dev mpi-default-bin \
        wget coreutils clang valgrind \
        python-lxml python-psutil

WORKDIR /root

# CMake 3.5.0
RUN wget https://www.cmake.org/files/v3.5/cmake-3.5.0.tar.gz
RUN echo "4a10116e061bbe806ffdd5164aca7780b0e98f4e  cmake-3.5.0.tar.gz" > cmake-3.5.0.tar.gz.sha1
RUN sha1sum -c cmake-3.5.0.tar.gz.sha1
RUN tar xf cmake-3.5.0.tar.gz
WORKDIR /root/cmake-3.5.0
RUN ./configure
RUN make
RUN make install

#
# Create user, since mpiexec doesn't like to run as root
#
RUN useradd -ms /bin/bash gitlab-ci

# Copy code into image
RUN  mkdir              /home/gitlab-ci/umit
COPY .                  /home/gitlab-ci/umit
RUN  chown -R gitlab-ci /home/gitlab-ci/umit

# Finally, make us run as gitlab-ci
USER gitlab-ci
WORKDIR /home/gitlab-ci/umit

# docker doesn't copy empty directories for some reason
RUN mkdir FMILibrary-2.0.1/ThirdParty/Expat/expat-2.1.0/src
RUN mkdir build
RUN mkdir build-clang
WORKDIR /home/gitlab-ci/umit/build
RUN cmake .. -G Ninja
RUN ninja install
WORKDIR /home/gitlab-ci/umit/build-clang
RUN cmake .. -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
RUN ninja install
