clear rod_sim rod.oct


rod_parameters = struct( ...
			 "N", 20, ...
			 "mass", 100, ...
			 "stiffness", 1e2, ... 
			 "tau", 0.1, ...
			 "driver_stiffness1", 0, ...
			 "driver_relaxation1", 0, ...
			 "driver_stiffnessN", 0, ...
			 "driver_relaxationN", 0);

rod_init_state = struct( ... 
		"x1", 1, ...
		"xN", -1, ...
		"v1", 0, ...
		"vN", 0, ...
		"a1", 0, ...
		"aN", 0, ...
		"dx1", 0, ...
		"dxN", 0, ...
		"f1", 0, ...
		"fN", 0, ...
		"driver_f1", 0, ...
		"driver_fN", 0, ...
		"v_drive1", 0, ...
		"v_driveN",  0, ...
		"step",  1/100 ...
	      );

x = zeros( rod_parameters.N, 1 );
mid =  floor( rod_parameters.N / 2 ); 
x(1:mid) = linspace( 0, 1, mid);
x(mid:end) = linspace( 1, 0, rod_parameters.N - mid + 1);
v = zeros( rod_parameters.N, 1 );
x0 = x;
v0 = v;

X = [x'];
V = [v'];
T = [ zeros( rod_parameters.N - 1 ,  1 )' ];
steps = 3000;


samples = 150;
for i = 1:steps
  [x, v, tq] = rod_sim( rod_parameters, rod_init_state, x, v, 1 ); 
  X = [ X; x' ];
  V = [ V; v' ];
  T = [ V; v' ];
endfor 
stride = ceil( steps / samples );
surf( X(1:stride:end, :) );

