%% 
%% Fairly realistic configuration with stiff couplings to the outside, small
%% inertia on the clutch plates, and moderately heavy load of 10 tons
%%
%%  Initial conditions are 10 rads per second from the driver.
%% 
%%
experiment1 = struct( ...
		      'omega_in' , 10, ...
		      'k_coupling_1' , 1e8, ...
		      'd_coupling_1' , 1e4, ...
		      'j1_inv' , 1 / 4, ...
		      'j2_inv' , 1/ 8, ...
		      'j3_inv' , 1 / 1e4, ...
		      'k_coupling_2' , 1e8, ...
		      'd_coupling_2' , 1e3, ...
		      'c_damping' , 1e4, ...
		      'x0', [ 0;0;0;0;0;0;0] ...
		    );

experiment2 = struct( ...
		      'omega_in' , 10, ... 
		      'k_coupling_1' , 0*1e6, ...
		      'd_coupling_1' , 0*1e4, ...
		      'j1_inv' , 1/10, ...
		      'j2_inv' , 1/10, ...
		      'j3_inv' , 1 / 1e-2, ...
		      'k_coupling_2' , 1e4, ...
		      'd_coupling_2' , 1*1e4, ...
		      'c_damping' , 10, ...
		      'x0', [ 0;15;0;0;0;0;0] ...
		    );
ee = experiment1;



simclutch = @(t, x ) [ ... 
		       x( 2 );  ... 
		       ee.j1_inv * ( - ee.d_coupling_1 * ( x( 2 ) - ee.omega_in ) - ee.k_coupling_1 *  x( 3 ) ... 
				     - fclutch( x( 1 ) - x( 4 ), x( 2 ) - x( 5 ), ee.c_damping ) ); ...
		       x( 2 ) - ee.omega_in; ...
		       x( 5 ); ...
		       ee.j2_inv * ( + fclutch( x( 1 ) - x( 4 ), x( 2 ) - x( 5 ), ee.c_damping  ) -ee.k_coupling_2 * ( x( 4 ) - x( 6 ) ) ... 
				     - ee.d_coupling_2 * ( x( 5 ) - x( 7 ) )  ); ...
		       x( 7 ); ... 
		       ee.j3_inv * (  ee.k_coupling_2 * ( x( 4 ) - x( 6 ) ) + ee.d_coupling_2 * ( x( 5 ) - x( 7 ) )  );
		     ];

jphi      = @(x) fclutch_dphi_derivative  ( x( 1 ) - x( 4 ), x( 2 ) - x( 5 )) ; 
%jomega    = @(x) fclutch_domega_derivative( x( 1 ) - x( 4 ), x( 2 ) - x( 5 ), ee.c_damping ) ; 

jacobian = @(t, x) [ ... 
		     0, 1,  0, 0, 0, 0, 0; ...
		     ee.j1_inv * [ -jphi( x ), -ee.d_coupling_1-ee.c_damping, -ee.k_coupling_1,  jphi( x ), +ee.c_damping, 0, 0]; ...
		     0, 1,  0, 0, 0, 0, 0; ...
		     0, 0, 0, 0, 1, 0, 0; ...
		     ee.j2_inv*[jphi( x ), ee.c_damping, 0, -jphi( x )-ee.k_coupling_2, -ee.c_damping-ee.d_coupling_2, ee.k_coupling_2, +ee.c_damping]; ...
		     0, 0, 0, 0, 0, 0, 1;
		     ee.j3_inv*[0, 0, 0, ee.k_coupling_2, ee.d_coupling_2, -ee.k_coupling_2, -ee.d_coupling_2] ]; 

%% if 0
%%  % get different values using Jacobian evaluated in the different regimes. 
%%   M = {A1, A2, A3, A4};
%%   R = {A1, A2, A3, A4};
%%   T = cell();

%%   IA  = eye(size(A1));
%%   h = 1e-3;
%%   E = [];
%%   for i = 1:length(M)
%%     a0 = h * M{i};
%%     a = a0;
%%     r = IA;
%%     for k=1:5
%%       r += a / factorial( k );
%%       a = a * a0;
%%     end
%%     R{ i } = r;
%%     E = [E, eigs( r ) ];
%% 				%  T{end+1} = M{i} \ ( r - IA );
%%   end

%% end

vopt = odeset ('RelTol', 1e-6, 'AbsTol', 1e-6, 'NormControl', 'on', 'InitialStep', 1e-2, 'MaxStep', 0.1, ...
	       'Jacobian', jacobian);
%sol = ode45( simclutch, [0, 1 ], ee.x0,  vopt );
[T, X] = ode23s( simclutch, [0, 0.5 ], ee.x0,  vopt );
%sol = ode23s( simclutch, [0, 10 ], ee.x0,  vopt );
%sol = ode15s( simclutch, [0, 10 ], ee.x0,  vopt );
%sol  = struct('x', T, 'y', X);
%sol = odebwe( simclutch, [0, 10 ], ee.x0,  vopt );
if ( size( sol.x, 2 ) ~= 1  )
  sol.x = sol.x';
  sol.y = sol.y';
end
if ( 0 )
figure(1);
H =  plot(sol.x, [sol.y(:,1)-sol.y(:, 4), sol.y(:,2)-sol.y(:,5), sol.y(:, 7)] );
set(findall(H, '-property', 'linewidth'), 'linewidth', 2);
legend('x1-x2', 'v1-v2','v3', 'location', 'northeast');

figure(2);
H = plot(sol.y(:, 1) - sol.y(:, 4 ), sol.y(:, 5), '.-');
set(findall(H, '-property', 'linewidth'), 'linewidth', 2);
title('phase plot: angle difference  vs speed');
xlabel('dx');
ylabel('v2');

figure(3);
H = plot(sol.x, sol.y(:, 1) - sol.y(:, 4 ) );
set(findall(H, '-property', 'linewidth'), 'linewidth', 2);
title('Angle differences');

figure(4);
H = plot(sol.x, sol.y(:, [2,5,7]));
legend('v1', 'v2','v3');
title('Velocities');
set(findall(H, '-property', 'linewidth'), 'linewidth', 2);
endif
