
%% 
%% Fairly realistic configuration with stiff couplings to the outside, small
%% inertia on the clutch plates, and moderately heavy load of 10 tons
%%
%%  Initial conditions are 10 rads per second from the driver.
%% 
%%
experiment1 = struct( ...
		      'omega_in' , 10, ...
		      'k_coupling_1' , 1e6, ...
		      'd_coupling_1' , 1e4, ...
		      'j1_inv' , 1 / 4, ...
		      'j2_inv' , 1/ 8, ...
		      'j3_inv' , 1 / 1e4, ...
		      'k_coupling_2' , 1e6, ...
		      'd_coupling_2' , 1e3, ...
		      'c_damping' , 1000, ...
		      'x0', [ 0;0;0;0;0;0;0] ...
		    );

experiment2 = struct( ...
		      'omega_in' , 10, ... 
		      'k_coupling_1' , 0*1e6, ...
		      'd_coupling_1' , 0*1e4, ...
		      'j1_inv' , 1/10, ...
		      'j2_inv' , 1/10, ...
		      'j3_inv' , 1 / 1e-2, ...
		      'k_coupling_2' , 1e4, ...
		      'd_coupling_2' , 1*1e4, ...
		      'c_damping' , 10, ...
		      'x0', [ 0;15;0;0;0;0;0] ...
		    );
ee = experiment1;



simclutch = @(t, x ) [ ... 
		       x( 2 );  ... 
		       ee.j1_inv * ( - ee.d_coupling_1 * ( x( 2 ) - ee.omega_in ) - ee.k_coupling_1 *  x( 3 ) ... 
				     - fclutch( x( 1 ) - x( 4 ), x( 2 ) - x( 5 ), ee.c_damping ) ); ...
		       x( 2 ) - ee.omega_in; ...
		       x( 5 ); ...
		       ee.j2_inv * ( + fclutch( x( 1 ) - x( 4 ), x( 2 ) - x( 5 ), ee.c_damping  ) -ee.k_coupling_2 * ( x( 4 ) - x( 6 ) ) ... 
				     - ee.d_coupling_2 * ( x( 5 ) - x( 7 ) )  ); ...
		       x( 7 ); ... 
		       ee.j3_inv * (  ee.k_coupling_2 * ( x( 4 ) - x( 6 ) ) + ee.d_coupling_2 * ( x( 5 ) - x( 7 ) )  );
		     ];

jphi      = @(x) fclutch_dphi_derivative  ( x( 1 ) - x( 4 ), x( 2 ) - x( 5 )) ; 
%jomega    = @(x) fclutch_domega_derivative( x( 1 ) - x( 4 ), x( 2 ) - x( 5 ), ee.c_damping ) ; 

jacobian = @(t, x) [ ... 
		     0, 1,  0, 0, 0, 0, 0; ...
		     ee.j1_inv * [ -jphi( x ), -ee.d_coupling_1-ee.c_damping, -ee.k_coupling_1,  jphi( x ), +ee.c_damping, 0, 0]; ...
		     0, 1,  0, 0, 0, 0, 0; ...
		     0, 0, 0, 0, 1, 0, 0; ...
		     ee.j2_inv*[jphi( x ), ee.c_damping, 0, -jphi( x )-ee.k_coupling_2, -ee.c_damping-ee.d_coupling_2, ee.k_coupling_2, +ee.c_damping]; ...
		     0, 0, 0, 0, 0, 0, 1;
		     ee.j3_inv*[0, 0, 0, ee.k_coupling_2, ee.d_coupling_2, -ee.k_coupling_2, -ee.d_coupling_2] ]; 


x = rand(7,1);
pert = 1e-3;

JJ = [];
for i=1:7
  xp = x; 
  xp(i) += pert;

  JJ = [JJ, ( simclutch(0, xp) - simclutch( 0, x ) ) / pert ];

endfor

A = jacobian(0, x ) ;
