TOP_DIR = 
default:
	gcc -g two_masses.c ../../../templates/cgsl/src/gsl-interface.c \
	-DCONSOLE  -I../../../templates/cgsl/include \
	-I../../../templates/fmi2 -lgsl -lgslcblas -lm  \
	-I../../../../build/install/include  -o two_masses

